### ISSUE TITLE
Can't see all content on page with toolbar-bottom

### ISSUE THREAD

**Issue by KrunchMuffin** [nolimits4web/Framework7#1118]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.4.2
* Platform and Target: CORDOVA, ANDROID

### What you did
Added a `toolbar-bottom` with tabs to a page and dynamically added content to the active tab.

        <div class="toolbar toolbar-bottom tabbar">
            <div class="toolbar-inner">
                <a href="#seriesTab" class="tab-link active">
                    <i class="icon icon-play"></i>
                </a>
                <a href="#historyTab" class="tab-link">
                    <i class="icon icon-clock"></i>
                </a>
                <a href="#wantedTab" class="tab-link">
                    <i class="icon icon-alert"><span class="badge bg-red">5</span></i>
                </a>
                
            </div>
        </div>
        
        <div class="page-content">
            
            <div class="tabs">
                
                
                <div class="tab active" id="seriesTab">
                </div>
                
                <div class="tab" id="historyTab">
                    ... Tab 2 content goes here ...
                </div>
                
                <div class="tab" id="wantedTab">
                    ... Tab 3 content goes here ...
                </div>
            </div>
        </div>

 **onPageBeforeInit** - this adds about 100 lines to the output
`  $$.each(data, function(index,value){
      $$('#seriesTab').append('Title: ' +value.title+'<br>')
  })`

### Expected Behavior
Should be able to scroll and see all content.

### Actual Behavior
last two lines of output are blocked by `toolbar-bottom`

![image](https://cloud.githubusercontent.com/assets/1037197/18407866/367b7962-76eb-11e6-9409-023d960612ca.png)

**Comment by valnub** [comment]
Hi, to your page add class `toolbar-fixed` like this:

`<div data-page="somepage" class="page toolbar-fixed">`

Does this fix your issue?

**Comment by valnub** [comment]
Closed due to no reaction. Adding `toolbar-fixed` should fix the issue most likely.

**Comment by KrunchMuffin** [comment]
Sorry. Haven't been on that project and I moved to top bar.

**Comment by cyberbeat** [comment]
This is still a problem. toolbar-fixed adds a padding-bottom of 44px to the page-content. This is wrong for the bottom "tab-bar", which is 55px height. Another problem by this solution is, that the scrollbar still hides behind the tabbar.
